name: cart-cicd

on:
  push:
    branches: [ main ]
    paths:
    - 'src/cart/**'
    - '.github/workflows/cart-cicd.yml'
  pull_request:
    branches: [ main ]
    paths:
    - 'src/cart/**'
    - '.github/workflows/cart-cicd.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.302
    
    # dotnet build and publish
    - name: Build with dotnet
      run: dotnet build --configuration Release
      working-directory: ./src/cart
    - name: dotnet publish
      run: |
        dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/cart'       working-directory: ./src/cart
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: micro-cart-web-2tg # Replace with your app name
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/cart' 